###

// create user
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "name": "Xavier Yeo",
    "email": "xa0001eo@e.ntu.edu.sg",
    "password": "testtesttest",
    "year": "3",
    "modulesTaken": []
}

###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "xa0001eo@e.ntu.edu.sg",
    "password": "testtesttest"
}